# Generated by Django 5.1.2 on 2024-10-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id_buyer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id_owner', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=250, verbose_name='Улица')),
                ('number_of_street', models.PositiveIntegerField(verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('offered_price', models.PositiveIntegerField(verbose_name='Предполагаемая цена')),
                ('meeting_date', models.DateField(verbose_name='Дата встречи')),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carshop.buyer')),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carshop.car')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_make_order', models.DateField(auto_now=True)),
                ('id_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carshop.order')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carshop.owner'),
        ),
        migrations.AddField(
            model_name='car',
            name='id_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carshop.storage'),
        ),
    ]
