# Generated by Django 5.1.2 on 2024-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0003_alter_storage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='owner',
            field=models.ManyToManyField(to='carshop.owner'),
        ),
    ]
